import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Box, Typography} from '@mui/material'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <Box>
          <Typography component="h1" variant="h3" color="primary.main">Hello</Typography>
             <Link
                 href={{
                     pathname: '/contact',
                     query: { name: 'test' },
                 }}
             >
                 About
             </Link>
         </Box>
      </main>
    </>
  )
}
